### PR TITLE
Switch to at_compile_time since compile_time has been officially deprecated

### PR DESCRIPTION
**Pull request by ramereth**
I ran into this problem running Chef 12.1+ as it failed during the run instead of just a warning.

### CODE REVIEW

**Comment by ramereth** [comment]
Any updates on this?

**Comment by ramereth** [comment]
Friendly prod

**Comment by lopaka** [comment]
Hello @ramereth 

We appreciate your contribution to our cookbooks. Development and testing of our cookbooks will commence in the very near future, at which time we can validate and merge your changes.  So, stay tuned!

Thanks,
Lopaka

**Comment by ramereth** [comment]
@lopaka thanks for the update. This now breaks if you use chef-client 12.5.x so it would be advisable to get this merged ASAP.

**Comment by ramereth** [comment]
ping

**Comment by rshade** [comment]
@ramereth if you don't mind can you update the version in metadata and changelog. I will merge today

**Comment by ramereth** [comment]
@rshade done!

**Comment by rshade** [comment]
@ramereth looks like I have to fix testing

**Comment by rshade** [comment]
I have updated, can you merge and re-submit @ramereth. Sorry about all the trouble

**Comment by ramereth** [comment]
@rshade no worries, done and it looks like they passed!

**Comment by rshade** [comment]
Thanks @ramereth I merged ya.

**Comment by ramereth** [comment]
@rshade mind uploading it to the supermarket so it shows up in berks properly?

**Pull request merged**
